from typing import Protocol


class Store(Protocol):
    """One logical run: lock -> read -> atomic commit (including watermark)."""

    def initialize(self): ...
    def lock(self): ...
    def read(self, table: str, board_id: int | None = None) -> list[dict]: ...
    def commit(self, payload: dict[str, list[dict]], board_id: int): ...
