# Copiar para /etc/logrotate.d/sls-orcamento-pdd após ajustar o caminho.
/opt/sls_orcamento_pdd/logs/daily.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su root root
}
