-- PostgreSQL v3: ONLY the consumption table. Use CLI init-db (new) or migrate-single-table (legacy) to pair executor state.

CREATE SCHEMA IF NOT EXISTS orcamento;


CREATE TABLE IF NOT EXISTS orcamento.gold_projeto_status (
	interval_id TEXT NOT NULL,
	board_id BIGINT NOT NULL,
	item_id BIGINT NOT NULL,
	status_id TEXT NOT NULL,
	projeto_nome TEXT NOT NULL,
	status_nome TEXT NOT NULL,
	ordem_status_quadro INTEGER,
	status_final BOOLEAN NOT NULL,
	ordem_etapa INTEGER NOT NULL,
	passagem_numero_no_status INTEGER NOT NULL,
	eh_retorno BOOLEAN NOT NULL,
	eh_primeiro_registro BOOLEAN NOT NULL,
	eh_ultimo_registro BOOLEAN NOT NULL,
	entrada_status_utc TIMESTAMP WITH TIME ZONE NOT NULL,
	saida_status_utc TIMESTAMP WITH TIME ZONE,
	entrada_status_local TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	saida_status_local TIMESTAMP WITHOUT TIME ZONE,
	corte_utc TIMESTAMP WITH TIME ZONE NOT NULL,
	corte_local TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	duracao_minutos FLOAT NOT NULL,
	duracao_horas FLOAT NOT NULL,
	intervalo_aberto BOOLEAN NOT NULL,
	qualidade_historico TEXT NOT NULL,
	elegivel_comparacao BOOLEAN NOT NULL,
	horas_observadas_encerradas FLOAT,
	status_atual_id TEXT NOT NULL,
	status_atual_nome TEXT NOT NULL,
	projeto_ativo BOOLEAN NOT NULL,
	projeto_na_fila BOOLEAN NOT NULL,
	status_atual_divergente BOOLEAN NOT NULL,
	entrada_comprovada_utc TIMESTAMP WITH TIME ZONE,
	finalizado_em_utc TIMESTAMP WITH TIME ZONE,
	tempo_desde_entrada_horas FLOAT,
	tempo_status_atual_horas FLOAT,
	marca_chave TEXT,
	marca_nome TEXT,
	marca_situacao TEXT NOT NULL,
	talento_chave TEXT,
	talento_nome TEXT,
	talento_origem TEXT,
	talento_situacao TEXT NOT NULL,
	responsavel_orcamento TEXT,
	responsaveis_orcamento_json JSONB NOT NULL,
	quantidade_responsaveis_orcamento INTEGER NOT NULL,
	responsavel_situacao TEXT NOT NULL,
	talent_manager TEXT,
	gp TEXT,
	audiencia TEXT,
	conteudo TEXT,
	producao TEXT,
	pessoas_referencia_json JSONB NOT NULL,
	cadastro_referencia_utc TIMESTAMP WITH TIME ZONE,
	versao_regras TEXT NOT NULL,
	board_sk TEXT NOT NULL,
	item_sk TEXT NOT NULL,
	status_sk TEXT NOT NULL,
	PRIMARY KEY (interval_id),
	CONSTRAINT uq_gold_projeto_ordem UNIQUE (board_id, item_id, ordem_etapa),
	CONSTRAINT ck_gold_ordem CHECK (ordem_etapa >= 1 AND passagem_numero_no_status >= 1),
	CONSTRAINT ck_gold_marcadores CHECK (eh_primeiro_registro = (ordem_etapa=1) AND eh_retorno = (passagem_numero_no_status>1) AND intervalo_aberto=eh_ultimo_registro),
	CONSTRAINT ck_gold_fechamento CHECK (intervalo_aberto = (saida_status_utc IS NULL) AND entrada_status_utc < corte_utc AND (saida_status_utc IS NULL OR saida_status_utc BETWEEN entrada_status_utc AND corte_utc)),
	CONSTRAINT ck_gold_duracao CHECK (duracao_minutos >= 0 AND abs(duracao_minutos - extract(epoch FROM (coalesce(saida_status_utc,corte_utc)-entrada_status_utc))/60) < 0.00001 AND abs(duracao_horas*60-duracao_minutos) < 0.00001)
)

;

CREATE UNIQUE INDEX IF NOT EXISTS uq_gold_ultima_passagem ON orcamento.gold_projeto_status (board_id, item_id) WHERE intervalo_aberto;

CREATE INDEX IF NOT EXISTS ix_gold_projeto_status ON orcamento.gold_projeto_status (board_id, item_id, ordem_etapa);
